app_deteriora/urls.py
LOGIN_URL = 'signin'

# urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView

from .forms import CustomAuthenticationForm

from .views import (
    signup, semi, coro, neuro, my_view, neuro_grafico
)

urlpatterns = [
    path('', auth_views.LogoutView.as_view(template_name='app_deteriora/inicial.html')),
    path('signin/', auth_views.LoginView.as_view(template_name='app_deteriora/signin.html', authentication_form=CustomAuthenticationForm), name='signin'),
    path('accounts/profile/inicial', auth_views.LogoutView.as_view(template_name='app_deteriora/inicial.html')),
    path('signup', signup, name = 'signup'),
    path('accounts/profile/', semi, name = 'semi'),
    path('accounts/profile/semi', semi, name = 'semi'),
    path('accounts/profile/coro', coro, name = 'coro'),
    path('accounts/profile/neuro', neuro, name = 'neuro'),
    path('accounts/profile/my_view', my_view, name = 'my_view'),
    path('accounts/profile/neuro_grafico', neuro_grafico, name = 'neuro_grafico'),
]

django_/django_deteriora/app_deteriora/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import (
    inicial, signin, signup, semi, coro, neuro, get_date
)

urlpatterns = [
    path('', inicial, name = 'inicial'),
    path('signin', signin, name = 'signin'),
    path('signup', signup, name = 'signup'),
    path('semi', semi, name = 'semi'),
    path('coro', coro, name = 'coro'),
    path('neuro', neuro, name = 'neuro'),
    path('get_date', get_date, name='get_date'),
]

django_/django_deteriora/django_deteriora/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_deteriora.urls')),
]

django_deteriora/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_deteriora.urls')),
]

from django.conf import settings
from django.conf.urls.static import static



# add this code to serve static files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_deteriora/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission


class User(AbstractUser):
    # Add related_name argument to avoid clashes with the built-in User model
    groups = models.ManyToManyField(Group, related_name='customuser_set', blank=True)
    user_permissions = models.ManyToManyField(
        Permission, related_name='customuser_set', blank=True
    )

class MyUserCreationForm(models.Model):
    dados_de_login = ('username', 'email', 'password1', 'password2')
    
# Escolha de leitos para o botão Ação    
choices_leitos = [
            ('leito1', 'leito1'),
            ('leito2', 'leito2'),
            ('leito3', 'leito3')]

CHOICES_leitos = choices_leitos

class DataAtual(models.Model):
    leito = models.CharField(max_length=200, choices=CHOICES_leitos) 
    created_at = models.DateTimeField(auto_now_add=True)

# Escolha de leitos para o Gráfico Neuro 
choices_leitos_grafico = [
            ('A877', 'A877'),
            ('leito2', 'leito2'),
            ('leito3', 'leito3')]

CHOICES_leitos = choices_leitos_grafico

class LeitosGraficos(models.Model):
    leitos_graficos_neuro = models.CharField(max_length=200, choices=CHOICES_leitos) 
   

dj_teste_2 - Copia/django_deteriora/app_deteriora/models.py
from django.db import models

from datetime import date

class MyModelDateHj(models.Model):
    col3 = models.DateField()

class MyModelDateHj2(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

dj_teste_btn_dh_on_click/django_deteriora/app_deteriora/models.py
from django.db import models

from datetime import date

class MyModelDateHj(models.Model):
    col3 = models.DateField()

class MyModelDateHj2(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

django_ - Copia/django_deteriora/app_deteriora/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission

class User(AbstractUser):
    # Add related_name argument to avoid clashes with the built-in User model
    groups = models.ManyToManyField(Group, related_name='customuser_set', blank=True)
    user_permissions = models.ManyToManyField(
        Permission, related_name='customuser_set', blank=True
    )

django_teste/django_deteriora/app_deteriora/models.py
from django.db import models

class MyModel(models.Model):
    col1 = models.CharField(max_length=50)

class MyModelDate(models.Model):
    col2 = models.CharField()

import datetime

class MyModelDateHj2(models.Model):
    col3 = models.CharField(default=datetime.datetime.now)

django_teste_btn_js_ok/django_deteriora/app_deteriora/models.py
from django.db import models

django_teste_resistro_dh/django_deteriora/app_deteriora/models.py
from django.db import models

class MyModel(models.Model):
    col1 = models.CharField(max_length=50)

class MyModelDate(models.Model):
    col2 = models.DateTimeField()

app_deteriora/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm


from .models import DataAtual,LeitosGraficos
from django.forms import ModelForm

class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
class DataAtualForm(ModelForm):
    class Meta:
        model = DataAtual
        fields = '__all__'

class LeitosGraficosForm(ModelForm):
    class Meta:
        model = LeitosGraficos
        fields = '__all__'


class CustomAuthenticationForm(AuthenticationForm):
    error_messages = {
        'invalid_login': "Senha incorreta",
    }

dj_teste_2 - Copia/django_deteriora/app_deteriora/forms.py
from .models import MyModelDateHj
from django.forms import ModelForm


class VariaveisForm(ModelForm):
    class Meta:
        model = MyModelDateHj
        fields = '__all__'

dj_teste_btn_dh_on_click/django_deteriora/app_deteriora/forms.py
from .models import MyModelDateHj
from django.forms import ModelForm


class VariaveisForm(ModelForm):
    class Meta:
        model = MyModelDateHj
        fields = '__all__'

django_ - Copia/django_deteriora/app_deteriora/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


'''login'''
class EmailPasswordForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

'''cadastro'''

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class EmailPasswordSignupForm(UserCreationForm):
    email = forms.EmailField(required=True)
    username = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(EmailPasswordSignupForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']
        if commit:
            user.save()
        return user

django_/django_deteriora/app_deteriora/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import MyUserCreationForm

class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

django_teste/django_deteriora/app_deteriora/forms.py
from .models import MyModel, MyModelDate, MyModelDateHj
from django.forms import ModelForm


class VariaveisForm(ModelForm):
    class Meta:
        model = MyModelDateHj
        fields = '__all__'

django_teste_resistro_dh/django_deteriora/app_deteriora/forms.py
from .models import MyModel, MyModelDate
from django.forms import ModelForm

class VariaveisForm(ModelForm):
    class Meta:
        model = MyModel
        fields = '__all__'

class VariaveisForm(ModelForm):
    class Meta:
        model = MyModelDate
        fields = '__all__'

django_username_password_ok/django_deteriora/app_deteriora/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import MyUserCreationForm

class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

app_deteriora/views.py
# Carregar pacotes django
# from django.http import request
# from django.contrib.auth.models import User

from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.contrib.staticfiles import finders
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Carregar pacotes python
# import csv

from datetime import datetime
import pandas as pd 
import matplotlib.pyplot as plt
import os
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

# Forms
from .forms import MyUserCreationForm, MyUserCreationForm, DataAtualForm, LeitosGraficosForm

# Models
from .models import DataAtual, LeitosGraficos



# Pagina signup
def signup(request):
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return render(request, 'app_deteriora/signin.html', {'form': form})
    else:
        form = MyUserCreationForm()
    return render(request, 'app_deteriora/signup.html', {'form': form})




# Pagina semi
@login_required
@csrf_exempt
def semi(request):
        form_date = DataAtualForm(request.POST or None)
        dados3 = {}
        dados3['form_date'] = form_date
        if form_date.is_valid():
            form_date.save()
            return render(request, 'app_deteriora/acao_registrada.html')
        return render(request, 'app_deteriora/semi.html',dados3)



@login_required
def my_view(request):
    my_objects = DataAtual.objects.all()
    return render(request, 'app_deteriora/my_template.html', {'my_objects': my_objects})

@login_required
def neuro(request):
    csv_path = finders.find('tbl_teste_.csv')
    df = pd.read_csv(csv_path, sep = ',')

     # Convertendo a variavel para o tipo datetime
    df['exec_dt_tm'] = pd.to_datetime(df['exec_dt_tm'])

    # Renomeando as colunas 
    df = df.rename(columns = {'exec_dt_tm':'data predição', 'prob_norm': 'probabilidade deterioração'})
    
    # Selecionando as colunas desejadas
    df_table = df[['data predição', 'leito', 'probabilidade deterioração']]

    # Dividindo as semis de acordo com os leitos
    df_table['leito_n'] = df_table['leito'].str.split('A').str[1].astype('int')
    df_table_neuro = df_table[df_table['leito_n'] > 873]

    df_table_neuro = df_table_neuro.pivot(index='data predição', columns='leito', values='probabilidade deterioração')
    df_table_neuro = df_table_neuro.fillna('')
    df_table_neuro = df_table_neuro.reset_index()
    nomes = df_table_neuro.columns.to_list()
    dados = df_table_neuro.values
    df_table_neuro = pd.DataFrame(dados, columns=nomes)

    # Selecionando as últimas cincos horas de predição 
    df_table_neuro['dif_dt_pred'] = pd.to_datetime(datetime.now(), format = '%Y-%m-%d %H:%M:%S') - pd.to_datetime(df_table_neuro['data predição'], format = '%Y-%m-%d %H:%M:%S')
    df_table_neuro['dif_dt_pred'] = (df_table_neuro['dif_dt_pred'].dt.days)*3600 + df_table_neuro['dif_dt_pred'].dt.seconds
    df_table_neuro = df_table_neuro[df_table_neuro['dif_dt_pred'] < 18000]
    del df_table_neuro['dif_dt_pred']
        
    # Convert the DataFrame to an HTML table
    table_html = df_table_neuro.to_html(index=False)
    

    dados_table = {'table_html': table_html}
 
    form_graficos_neuro = LeitosGraficosForm(request.POST or None)
    dados_grafico = {}
    dados_grafico['form_graficos_neuro'] = form_graficos_neuro

    if form_graficos_neuro.is_valid():
        form_graficos_neuro.save()
        for e in LeitosGraficos.objects.all():
            leito_neuro = e.leitos_graficos_neuro

        csv_path = finders.find('tbl_teste_.csv')
        df = pd.read_csv(csv_path, sep = ',')

        # Convertendo a variavel para o tipo datetime
        df['exec_dt_tm'] = pd.to_datetime(df['exec_dt_tm'])

        # Renomeando as colunas 
        df = df.rename(columns = {'exec_dt_tm':'data predição', 'prob_norm': 'probabilidade deterioração'})
            
        # Selecionando as colunas desejadas
        df_table = df[['data predição', 'leito', 'probabilidade deterioração']]

        # Dividindo as semis de acordo com os leitos
        df_table['leito_n'] = df_table['leito'].str.split('A').str[1].astype('int')
        df_table_neuro = df_table[df_table['leito_n'] > 873]

        # Selecionando o leito
        leito = 'A877'

        # Selecionado os dados do leito desejado
        df1 = df[df['leito'] == leito]
        df1

        # Seleção das variáveis desejadas
        df1 = df1[['data predição', 'probabilidade deterioração']]

        # Definindo o eixo X do Gráfico 
        df1.index = df1['data predição']
        del df1['data predição']

        # Gráfico da probabilidade de deterioração 
        df1.plot(figsize=(15, 6),marker='o')
        plt.xlabel("Data e hora da predição")
        plt.ylabel("Probabilidade de deterioração (%) ")
        plt.title("Probabilidades de deterioração do leito: {}".format(leito) + " da neuro")
        plt.savefig('my_plot.png')
        return render(request, 'app_deteriora/neuro_grafico.html')

    context = {}
    context.update(dados_table)
    context.update(dados_grafico)

    return render(request, 'app_deteriora/neuro.html',context)

@login_required
def neuro_grafico(request):
    return render(request, 'app_deteriora/neuro_grafico.html')

# Pagina coro
@login_required
def coro(request):
    return render(request, 'app_deteriora/coro.html')

dj_teste_2 - Copia/django_deteriora/app_deteriora/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import redirect
import datetime
from .models import MyModelDateHj
from .forms import VariaveisForm


def acao_registrada(request):
    return render(request, 'app_deteriora/acao_registrada.html')

'''
def semi(request):
    formt = VariaveisForm(request.POST or None)
    if formt.is_valid():
        formt.save()
        return render(request, 'app_deteriora/acao_registrada.html')
    return render(request, 'app_deteriora/semi.html')
'''

from django.shortcuts import render
from .models import MyModelDateHj2


from django.shortcuts import redirect
from datetime import datetime

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import MyModelDateHj2

@csrf_exempt
def semi(request):
    if request.method == 'POST':
        date = MyModelDateHj2.objects.create()
        return render(request, 'app_deteriora/acao_registrada.html')
    return render(request, 'app_deteriora/semi.html')


def my_view(request):
    my_objects = MyModelDateHj2.objects.all()
    return render(request, 'app_deteriora/my_template.html', {'my_objects': my_objects})

import pandas as pd

def neuro(request):
    my_data = pd.DataFrame({'name': ['John', 'Jane', 'Bob'], 'age': [25, 30, 20]})
    
    # Convert the DataFrame to an HTML table
    table_html = my_data.to_html(index=False)

    context = {'table_html': table_html}
    return render(request, 'app_deteriora/neuro.html', context)

dj_teste_btn_dh_on_click/django_deteriora/app_deteriora/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import redirect
import datetime
from .models import MyModelDateHj
from .forms import VariaveisForm


def acao_registrada(request):
    return render(request, 'app_deteriora/acao_registrada.html')

'''
def semi(request):
    formt = VariaveisForm(request.POST or None)
    if formt.is_valid():
        formt.save()
        return render(request, 'app_deteriora/acao_registrada.html')
    return render(request, 'app_deteriora/semi.html')
'''

from django.shortcuts import render
from .models import MyModelDateHj2


from django.shortcuts import redirect
from datetime import datetime

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import MyModelDateHj2

@csrf_exempt
def semi(request):
    if request.method == 'POST':
        date = MyModelDateHj2.objects.create()
        return render(request, 'app_deteriora/acao_registrada.html')
    return render(request, 'app_deteriora/semi.html')


def my_view(request):
    my_objects = MyModelDateHj2.objects.all()
    return render(request, 'app_deteriora/my_template.html', {'my_objects': my_objects})

django_ - Copia/django_deteriora/app_deteriora/templates/app_deteriora/inicial.html
{% load static %}

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
	<head>

		<link rel="shortcut icon" type="image/x-icon" href="{% static 'logo_hiae.png' %}">
		
		<title> Projeto Deterioração </title>

		<meta name="description" content="App deterioração">
		<meta charset="utf-8" />

		<link rel="stylesheet" href="{% static 'inicial.css' %}">

	</head>
	<body>
		<br>
		<br>
		<br>
		<br>
		<div>
			<img src="{% static 'logo_hiae.png' %}" alt="logo" class="img2">
		</div>

		<br>
		<br>
		<br>
		<br>

		<div>
			<h1> Deterioração clínica </h1>
			<h2> Departamento de Pacientes Graves (DPG)</h2>
		</div>
		<br>
		<br>

		<br>
		<br>
		<br>
		<br>

		<div>
			<a class="link" tabindex="-1" aria-disabled="true" href="login">
				<input value="Início" class="login" type="button">
			</a>
		</div>	
		<br>


		<br>
		<br>
	</body>
</html>

django_ - Copia/django_deteriora/app_deteriora/templates/app_deteriora/login.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

	<head>
		<meta charset="utf-8">

		<link rel="shortcut icon" type="image/x-icon" href="{% static 'logo_hiae.png' %}">
		
		<title> Login </title>
		
		<link rel="stylesheet" href="{% static 'login.css' %}">

	</head>

	<body>

		<div id="rectangle"></div>
		<div>
			<img src="{% static 'logo_hiae.png' %}" alt="logo" class="img2">
		</div>

		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>

		<div class="div2">
			<h1 class="h1_acesse_aq"> Acesse aqui </h1>
		</div>
		<div class="container">
			{% if form.errors %}
			<p class="error">Please correct the errors below.</p>
			{% endif %}

			<form method="post" action="{% url 'login' %}">
				{% csrf_token %}
				<label for="id_email">Email:</label>
				<input type="email" name="email" id="id_email" placeholder="Entre com seu email">
				<br>
				<label for="password" placeholder="Entre com sua senha">Senha:</label>
				<input type="password" name="password" id="password">
				<br>
				<button type="submit">Entrar</button>
			</form>
			
			

		</div>
			<br>
		<div class="container" style="background-color:#f1f1f1">
			<span class="psw">  <a href="#">Esqueci minha senha</a></span>
			<br>
			<br>
			<a class="link" tabindex="-1" aria-disabled="true" href="signup">
				<input value= "Cadastre aqui" class="btn_cadastro" type="button">
			</a>
		</div>
	</body>
</html>

django_ - Copia/django_deteriora/app_deteriora/templates/app_deteriora/neuro.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

	<head>
		<meta charset="utf-8">

		<link rel="shortcut icon" type="image/x-icon" href="{% static 'logo_hiae.png' %}">

		<title> Semi Neuro </title>
		
		<link rel="stylesheet" href="{% static 'neuro_e_coro.css'%}">

		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light nav_size">
			<a class="navbar-brand" href="">
				<img class = "nav_logo_size" src="{% static 'logo_hiae.png' %}" alt="">
			</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse font_size" id="navbarNav">
			  <ul class="navbar-nav">
				<li class="nav-item">
				  <a class="nav-link" href="semi">Home</a>
				</li>
				<li class="nav-item">
				  <a class="nav-link active" href="neuro">Neurologica <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="coro">Coronariana</a>
				  </li>
				<li class="nav-item">
				  <a class="nav-link" href="">Sair</a>
				</li>
			  </ul>
			</div>
		</nav>
		<div id="rectangle"></div>
	

		<br>
		<br>
		<br>
		<br>
		<div>
			<h1 class="h1_acesse_aq"> Painel com as probabilidades de deterioração para todos os leitos da neuro </h1>
		</div>
		
	</body>

</html>

django_ - Copia/django_deteriora/app_deteriora/templates/app_deteriora/semi.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

	<head>
		<meta charset="utf-8">

		<link rel="shortcut icon" type="image/x-icon" href="{% static 'logo_hiae.png' %}">

		<title> Home </title>
		
		<link rel="stylesheet" href="{% static 'semi.css'%}">

		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light nav_size">
			<a class="navbar-brand" href="semi">
				<img class = "nav_logo_size" src="{% static 'logo_hiae.png' %}" alt="">
			</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse font_size" id="navbarNav">
			  <ul class="navbar-nav">
				<li class="nav-item active">
				  <a class="nav-link" href="semi">Home <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
				  <a class="nav-link" href="neuro">Neurologica</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="coro">Coronariana</a>
				  </li>
				<li class="nav-item">
					<a class="nav-link" href="login">Sair</a>
				</li>
			  </ul>
			</div>
		</nav>
		

		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<div class="div2">
			<h1 class="h1_acesse_aq"> Escolha a semi que deseja visualizar </h1>
	
		<br>
		<br>
		<br>
			<a class="link" tabindex="-1" aria-disabled="true" href="neuro">
				<input value="Neuro" class="login_neuro" type="button">
			</a>
			<a class="link" tabindex="-1" aria-disabled="true" href="coro">
				<input value="Coro" class="login_coro" type="button">
			</a>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
			<input value="Ação" class="acao" type="button">
		</div>


	



	</body>

</html>

django_ - Copia/django_deteriora/app_deteriora/templates/app_deteriora/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

	<head>
		<meta charset="utf-8">

		<link rel="shortcut icon" type="image/x-icon" href="{% static 'logo_hiae.png' %}">
    
		<title> Cadastro </title>
		
		<link rel="stylesheet" href="{% static 'signup.css'%}">

	</head>

	<body>
    <div id="rectangle"></div>
		<div>
			<img src="{% static 'logo_hiae.png'%}" alt="logo" class="img2">
		</div>
    <br>
    <br>
    <br>
    <br>
    <div class="container">
      <h1>Cadastro</h1>
        
      <form method="post" action="{% url 'signup' %}">
        {% csrf_token %}
        <label for="username">Email Institucional:</label>
        <input type="text" name="username" id="username">
        <br>
        <label for="email">Email Institucional:</label>
        <input type="email" name="email" id="email">
        <br>
        <label for="password1">Senha:</label>
        <input type="password" name="password1" id="password1">
        <br>
        <label for="password2">Repita a senha:</label>
        <input type="password" name="password2" id="password2">
        <br>
        <button type="submit">Cadastrar</button>
      </form>
      
      <p>Criando uma conta você concorda com nossos <a href="#">Termos e Privacidade</a>.</p>
    
      <p>Já tem uma conta? <a href="login.html">Entre aqui </a>.</p>
    
      

    </div>
	</body>

</html>